# Generated by Django 4.2.4 on 2024-09-05 16:11

from django.db import migrations, models
import django.db.models.deletion
import foodapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('food', models.CharField(max_length=150)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=foodapp.models.getPictureName)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('image', models.ImageField(upload_to=foodapp.models.getPictureName)),
                ('ingredients', models.CharField(max_length=150)),
                ('flavour_profile', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=150)),
                ('ratings', models.FloatField()),
                ('amount', models.IntegerField(default=0)),
                ('availability', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.foodtype')),
            ],
        ),
    ]
